[package]
name = "hello_os_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "hello_os_rust"
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9"
x86_64 = "0.14.10"
spin = "0.9.8"